### ISSUE TITLE
Backend module only for administrator?

### ISSUE THREAD

**Issue by ax-ha** [Leuchtfeuer/typo3-aws-tools#13]
Hello,
thanks a lot for this great extension!
May I ask why you only allow admin users to access the backend module? 
I would really like to allow this for experienced editors as well without to allow them everything else.

Any ideas how I can achieve this?

Thanks a lot for your help!

**Comment by balasch** [comment]
Overwrite the access-settings via $TBE_MODULES. For TYPO3 v11.5 look at https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/BackendModule/BackendModuleApi/Index.html

**Comment by ax-ha** [comment]
Thank you, Marcus. I am still on version 11.5 and that was exactly the workaround which I have just used.

**Comment by balasch** [comment]
Great! Then I can close this issue here.
